### ISSUE TITLE
Pre-compiled version

### ISSUE THREAD

**Issue by salarmehr** [stefan-loewe/WinBinder#10]
Is there any pre-compiled version of the last version of WinBinder?
Why has not http://winbinder.org/ been updated since 2006?

**Comment by RainbowDashDC** [comment]
We don't have access to winbinder.org

We are sortof an unofficial continuation.

I'll see what I can do about getting you a new prebuild

**Comment by stefan-loewe** [comment]
We removed the binaries, because you can build it yourself. However, I see the comfort in having a precompiled version just for trying out/testing.

In commit 42ea9d5d5d5788ce40a10a1f8721b738c3603098 a precompiled version for PHP 5.6 was added.

You could pull that.

Or try to download them directly from https://github.com/stefan-loewe/WinBinder/tree/c9c8dfb5591a59ed5b2d2d0dc00c178e84ada528/binaries

Cheers
Stefan
